%% This Emakefile is called by common test during `rebar ct`
%% and it defines 'COMMON_TEST' macro to conditionaly compile
%% module, which uses maps syntax.
%% This one required because common test doesn't respect rebar's
%% `platform_define` option.

{jesse_schema_validator_tests, [{d, 'COMMON_TEST'}]}.
